// smithy-config.h - Runtime shape-specific MMVQ kernel config for kernel-anvil
//
// Loads per-model kernel configs from JSON at first dispatch.
// Generated by: kernel-anvil gguf-optimize model.gguf
// Docs: https://github.com/apollosenvy/kernel-anvil
//
// Config path (checked in order):
//   1. SMITHY_CONFIG env var
//   2. ~/.cache/smithy/<model_stem>.json
//   3. ~/.cache/smithy/default.json
//
// Format:
//   { "configs": { "<type_idx>": { "<n_bucket>,<k_bucket>": {"nwarps": N, "rows_per_block": R} } } }

#pragma once

#include <cstdio>
#include <cstdlib>
#include <cstring>

enum smithy_bucket : int {
    SMITHY_BUCKET_LE_128   = 0,
    SMITHY_BUCKET_LE_1024  = 1,
    SMITHY_BUCKET_LE_4096  = 2,
    SMITHY_BUCKET_LE_16384 = 3,
    SMITHY_BUCKET_GT_16384 = 4,
    SMITHY_NUM_BUCKETS     = 5,
};

struct smithy_shape_config {
    int nwarps;         // 0 = use default
    int rows_per_block; // 0 = use default
};

static inline smithy_bucket smithy_get_bucket(int dim) {
    if (dim <= 128)   return SMITHY_BUCKET_LE_128;
    if (dim <= 1024)  return SMITHY_BUCKET_LE_1024;
    if (dim <= 4096)  return SMITHY_BUCKET_LE_4096;
    if (dim <= 16384) return SMITHY_BUCKET_LE_16384;
    return SMITHY_BUCKET_GT_16384;
}

static smithy_shape_config smithy_configs[GGML_TYPE_COUNT][SMITHY_NUM_BUCKETS][SMITHY_NUM_BUCKETS] = {};
static bool smithy_configs_loaded  = false;
static bool smithy_load_attempted  = false;

static bool smithy_load_configs(const char * path) {
    FILE * f = fopen(path, "r");
    if (!f) return false;

    fseek(f, 0, SEEK_END);
    long size = ftell(f);
    fseek(f, 0, SEEK_SET);
    if (size <= 0 || size > 1024 * 1024) { fclose(f); return false; }

    char * buf = (char *)malloc(size + 1);
    if (!buf) { fclose(f); return false; }
    size_t nread = fread(buf, 1, size, f);
    fclose(f);
    buf[nread] = '\0';

    int loaded = 0;
    const char * p = strstr(buf, "\"configs\"");
    if (!p) { free(buf); return false; }

    while ((p = strchr(p, '"')) != NULL) {
        p++;
        int type_idx = -1;
        if (*p >= '0' && *p <= '9') {
            type_idx = atoi(p);
            p = strchr(p, '{');
            if (!p || type_idx < 0 || type_idx >= GGML_TYPE_COUNT) continue;

            const char * type_end = NULL;
            int depth = 1;
            const char * scan = p + 1;
            while (*scan && depth > 0) {
                if (*scan == '{') depth++;
                if (*scan == '}') depth--;
                if (depth == 0) { type_end = scan; break; }
                scan++;
            }
            if (!type_end) break;

            const char * entry = p;
            while (entry < type_end) {
                entry = strchr(entry, '"');
                if (!entry || entry >= type_end) break;
                entry++;

                int nb = -1, kb = -1;
                if (sscanf(entry, "%d,%d", &nb, &kb) == 2 &&
                    nb >= 0 && nb < SMITHY_NUM_BUCKETS &&
                    kb >= 0 && kb < SMITHY_NUM_BUCKETS) {

                    const char * nw_key  = strstr(entry, "\"nwarps\"");
                    const char * rpb_key = strstr(entry, "\"rows_per_block\"");
                    if (nw_key && nw_key < type_end && rpb_key && rpb_key < type_end) {
                        int nw = 0, rpb = 0;
                        const char * nw_val  = strchr(nw_key + 8, ':');
                        const char * rpb_val = strchr(rpb_key + 16, ':');
                        if (nw_val)  nw  = atoi(nw_val + 1);
                        if (rpb_val) rpb = atoi(rpb_val + 1);
                        if (nw > 0 && nw <= 32 && rpb > 0 && rpb <= 32) {
                            smithy_configs[type_idx][nb][kb] = {nw, rpb};
                            loaded++;
                        }
                    }
                }
                entry++;
            }
            p = type_end + 1;
        }
    }

    free(buf);
    smithy_configs_loaded = (loaded > 0);
    if (smithy_configs_loaded) {
        fprintf(stderr, "kernel-anvil: loaded %d shape configs from %s\n", loaded, path);
    }
    return smithy_configs_loaded;
}

static void smithy_try_load() {
    if (smithy_configs_loaded || smithy_load_attempted) return;
    smithy_load_attempted = true;

    const char * env_path = getenv("SMITHY_CONFIG");
    if (env_path && smithy_load_configs(env_path)) return;

    const char * home = getenv("HOME");
    if (!home) return;

    char default_path[512];
    snprintf(default_path, sizeof(default_path), "%s/.cache/smithy/default.json", home);
    smithy_load_configs(default_path);
}

static inline smithy_shape_config smithy_lookup(int type_idx, int nrows, int ncols) {
    smithy_try_load();
    if (!smithy_configs_loaded || type_idx < 0 || type_idx >= GGML_TYPE_COUNT) {
        return {0, 0};
    }
    return smithy_configs[type_idx][smithy_get_bucket(nrows)][smithy_get_bucket(ncols)];
}
