"""Generate shape-specialized HIP MMVQ kernels for llama.cpp.

Instead of tuning configs for the generic MMVQ kernel, this generates
purpose-built HIP kernels for specific (quant_type, N, K) shapes.
The generated kernels have:
- Hardcoded N, K dimensions (enables compiler optimizations)
- Optimal nwarps and rows_per_block for the specific shape
- Unrolled inner loops for known K
- Minimal cross-warp reduction (only as many warps as needed)

The output is a .hip file that hipcc compiles to a .so, which llama.cpp
can load via dlopen.
"""

from __future__ import annotations

import math
import os
import subprocess
import tempfile
from dataclasses import dataclass
from pathlib import Path


@dataclass
class KernelSpec:
    """Specification for a generated kernel."""
    quant_type: str  # "Q4_K", "Q6_K", etc.
    N: int           # output rows
    K: int           # input columns
    nwarps: int      # optimal warps per block
    rows_per_block: int  # output rows per block
    name: str = ""   # generated kernel function name

    def __post_init__(self):
        if not self.name:
            qt = self.quant_type.lower().replace("_", "")
            self.name = f"mmvq_{qt}_n{self.N}_k{self.K}_w{self.nwarps}_r{self.rows_per_block}"


def generate_q4k_kernel(spec: KernelSpec) -> str:
    """Generate a shape-specialized Q4_K MMVQ HIP kernel.

    This is a standalone GEMV kernel that dequantizes Q4_K weights and
    computes y = W @ x for a specific (N, K) shape.

    The key optimization over the generic kernel: the inner loop count
    is known at compile time, enabling full unrolling and eliminating
    the cross-warp reduction when nwarps=1.
    """
    N = spec.N
    K = spec.K
    nwarps = spec.nwarps
    rpb = spec.rows_per_block
    warp_size = 32
    threads_per_block = nwarps * warp_size

    if K % 256 != 0:
        raise ValueError(f"K must be divisible by 256 (Q4_K block size), got K={K}. "
                         f"This shape may use padding in llama.cpp.")

    # Q4_K constants
    QK_K = 256      # values per super-block
    QI4_K = 8       # int32s consumed per vec_dot call (qi)
    QR4_K = 2       # vec_dot iterations
    VDR = 2         # vector dot results per call

    blocks_per_row = K // QK_K
    blocks_per_iter = VDR * nwarps * warp_size // QI4_K
    num_iters = max(1, (blocks_per_row + blocks_per_iter - 1) // blocks_per_iter)

    grid_x = (N + rpb - 1) // rpb

    kernel = f"""// Generated by kernel-anvil for {spec.quant_type} N={N} K={K}
// nwarps={nwarps} rows_per_block={rpb} threads={threads_per_block}
// blocks_per_row={blocks_per_row} blocks_per_iter={blocks_per_iter} iterations={num_iters}
// Grid: ({grid_x}, 1, 1) Block: ({warp_size}, {nwarps}, 1)

#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>

// Q4_K block structure (144 bytes per 256 values)
struct block_q4_K {{
    __half2 dm;           // super-block scales (d, dmin)
    uint8_t scales[12];   // sub-block scales and mins (6-bit packed)
    uint8_t qs[128];      // 256 x 4-bit quants
}};

// Q8_1 block structure (input, quantized on-the-fly)
struct block_q8_1 {{
    __half2 ds;           // scale and sum (d, sum)
    int8_t qs[32];        // 32 x 8-bit quants
}};

static __device__ __forceinline__ int dp4a(int a, int b, int c) {{
#if defined(__gfx1100__) || defined(__gfx1101__) || defined(__gfx1102__) || defined(__gfx1200__) || defined(__gfx1201__)
    // RDNA3/4: signed-unsigned dot4 (sudot4)
    return __builtin_amdgcn_sudot4(true, a, true, b, c, false);
#else
    // RDNA2/GCN: signed dot4
    return __builtin_amdgcn_sdot4(a, b, c, false);
#endif
}}

extern "C"
__global__ __launch_bounds__({threads_per_block}, 1)
void {spec.name}(
    const void * __restrict__ weights,    // Q4_K weight matrix [N, K/256 blocks]
    const void * __restrict__ input_q8,   // quantized input [K/32 blocks of q8_1]
    float * __restrict__ output,          // output [N]
    const int stride_row                  // blocks per row (= K/256)
) {{
    const int tid = threadIdx.y * {warp_size} + threadIdx.x;
    const int row0 = blockIdx.x * {rpb};
"""

    if rpb > 1:
        kernel += f"""
    // Partial sums for {rpb} rows
    float tmp[{rpb}] = {{0.0f}};
"""
    else:
        kernel += """
    float tmp = 0.0f;
"""

    kernel += f"""
    const block_q4_K * bq4 = (const block_q4_K *)weights;
    const block_q8_1 * bq8 = (const block_q8_1*)input_q8;

    // Each thread processes blocks strided by blocks_per_iter
    const int iqs = {VDR} * (tid % ({QI4_K}/{VDR}));
    const int bq8_offset = {QR4_K} * ((iqs/2) / 4);  // QI8_1/2 = 4

    for (int kbx = tid / ({QI4_K}/{VDR}); kbx < {blocks_per_row}; kbx += {blocks_per_iter}) {{
        const int kby = kbx * ({QK_K}/32);  // QK8_1 = 32
"""

    # Inner loop over rows_per_block
    for i in range(rpb):
        indent = "        "
        kernel += f"""
{indent}// Row {i}
{indent}{{
{indent}    const block_q4_K * bk = bq4 + (row0 + {i}) * stride_row + kbx;

{indent}    // Load 4-bit quants
{indent}    const int * q4 = (const int *)(bk->qs + 16 * bq8_offset + 4 * ((iqs/2)%4));
{indent}    int v0 = q4[0];
{indent}    int v1 = q4[4];

{indent}    // Unpack 6-bit scales
{indent}    const uint16_t * scales = (const uint16_t *)bk->scales;
{indent}    uint16_t aux[2];
{indent}    const int j = bq8_offset/2;
{indent}    if (j < 2) {{
{indent}        aux[0] = scales[j+0] & 0x3f3f;
{indent}        aux[1] = scales[j+2] & 0x3f3f;
{indent}    }} else {{
{indent}        aux[0] = ((scales[j+2] >> 0) & 0x0f0f) | ((scales[j-2] & 0xc0c0) >> 2);
{indent}        aux[1] = ((scales[j+2] >> 4) & 0x0f0f) | ((scales[j-0] & 0xc0c0) >> 2);
{indent}    }}
{indent}    const uint8_t * sc = (const uint8_t *)aux;
{indent}    const uint8_t * m  = sc + 2;

{indent}    // Dot product with input
{indent}    float sumf_d = 0.0f;
{indent}    float sumf_m = 0.0f;
{indent}    #pragma unroll
{indent}    for (int qi = 0; qi < {QR4_K}; ++qi) {{
{indent}        const block_q8_1 * bq8i = bq8 + kby + bq8_offset + qi;
{indent}        float d8 = __low2float(bq8i->ds);
{indent}        const int * q8 = (const int *)bq8i->qs + ((iqs/2)%4);
{indent}        int u0 = q8[0];
{indent}        int u1 = q8[4];

{indent}        int v0i = (v0 >> (4*qi)) & 0x0F0F0F0F;
{indent}        int v1i = (v1 >> (4*qi)) & 0x0F0F0F0F;
{indent}        int dot1 = dp4a(v1i, u1, dp4a(v0i, u0, 0));
{indent}        int dot2 = dp4a(0x01010101, u1, dp4a(0x01010101, u0, 0));

{indent}        sumf_d += d8 * (dot1 * sc[qi]);
{indent}        sumf_m += d8 * (dot2 * m[qi]);
{indent}    }}

{indent}    float2 dm4f = __half22float2(bk->dm);
{indent}    {"tmp[" + str(i) + "]" if rpb > 1 else "tmp"} += dm4f.x * sumf_d - dm4f.y * sumf_m;
{indent}}}
"""

    kernel += "    }\n"

    # Cross-warp reduction
    if nwarps > 1:
        kernel += f"""
    // Cross-warp reduction via shared memory
    __shared__ float smem[{nwarps - 1}][{rpb}][{warp_size}];

    if (threadIdx.y > 0) {{
"""
        for i in range(rpb):
            kernel += f"        smem[threadIdx.y - 1][{i}][threadIdx.x] = {'tmp[' + str(i) + ']' if rpb > 1 else 'tmp'};\n"
        kernel += f"""    }}
    __syncthreads();
    if (threadIdx.y > 0) return;

    // Warp 0 accumulates
    #pragma unroll
    for (int w = 0; w < {nwarps - 1}; ++w) {{
"""
        for i in range(rpb):
            kernel += f"        {'tmp[' + str(i) + ']' if rpb > 1 else 'tmp'} += smem[w][{i}][threadIdx.x];\n"
        kernel += "    }\n"

    # Warp-level reduction (sum across lanes)
    # wave_size/2 = 16 for RDNA (wave32). GCN/CDNA (wave64) would need 32.
    # We only target RDNA2+ (all wave32).
    half_wave = warp_size // 2
    kernel += f"""
    // Warp reduction (wave{warp_size})
    #pragma unroll
    for (int offset = {half_wave}; offset > 0; offset >>= 1) {{
"""
    for i in range(rpb):
        t = f"tmp[{i}]" if rpb > 1 else "tmp"
        kernel += f"        {t} += __shfl_xor({t}, offset, 32);\n"
    kernel += "    }\n"

    # Write output
    kernel += f"""
    // Write output (only lane 0)
    if (threadIdx.x == 0) {{
"""
    for i in range(rpb):
        t = f"tmp[{i}]" if rpb > 1 else "tmp"
        kernel += f"        if (row0 + {i} < {N}) output[row0 + {i}] = {t};\n"
    kernel += "    }\n}\n"

    return kernel


def compile_kernel(hip_source: str, output_path: str, arch: str = "gfx1100") -> str:
    """Compile a HIP kernel to a shared library.

    Args:
        hip_source: HIP C++ source code.
        output_path: Path for the output .so file.
        arch: GPU architecture target (default gfx1100).

    Returns:
        Path to the compiled .so file.
    """
    with tempfile.NamedTemporaryFile(mode="w", suffix=".hip", delete=False) as f:
        f.write(hip_source)
        src_path = f.name

    try:
        cmd = [
            "hipcc",
            "--offload-arch=" + arch,
            "-shared", "-fPIC",
            "-O3",
            "-o", output_path,
            src_path,
        ]
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=60)
        if result.returncode != 0:
            raise RuntimeError(f"hipcc failed:\n{result.stderr}")
        return output_path
    finally:
        os.unlink(src_path)


def generate_model_kernels(
    shapes: dict[tuple[str, int, int], int],
    output_dir: str,
    arch: str = "gfx1100",
    optimal_configs: dict | None = None,
) -> list[tuple[KernelSpec, str]]:
    """Generate and compile optimized kernels for all shapes in a model.

    Args:
        shapes: Dict of (quant_type, N, K) -> count from GGUF parser.
        output_dir: Directory for compiled .so files.
        arch: GPU architecture.
        optimal_configs: Optional dict of (quant_type, N, K) -> {"nwarps": int, "rows_per_block": int}.
            If not provided, uses heuristic defaults.

    Returns:
        List of (KernelSpec, so_path) tuples.
    """
    os.makedirs(output_dir, exist_ok=True)
    results = []

    for (qt, n, k), count in shapes.items():
        if qt != "Q4_K":
            continue  # Only Q4_K for now

        # Get optimal config or use heuristic
        if optimal_configs and (qt, n, k) in optimal_configs:
            cfg = optimal_configs[(qt, n, k)]
            nwarps = cfg["nwarps"]
            rpb = cfg.get("rows_per_block", 1)
        else:
            # Heuristic: fewer warps for smaller K
            blocks_per_row = k // 256
            if blocks_per_row < 64:  # small_k
                nwarps = 2
                rpb = 2
            else:
                nwarps = 4
                rpb = 1

        spec = KernelSpec(quant_type=qt, N=n, K=k, nwarps=nwarps, rows_per_block=rpb)
        hip_src = generate_q4k_kernel(spec)

        so_path = os.path.join(output_dir, f"{spec.name}.so")
        try:
            compile_kernel(hip_src, so_path, arch)
            results.append((spec, so_path))
        except RuntimeError as e:
            print(f"  Failed to compile {spec.name}: {e}")

    return results
